# API Version also used to protect against API or Schema changes
# Actually, the available API versions are: 1
apiVersion: 1
# List of your proxies
# You can add as many proxies as you want with logic:
# 1 proxy per final domain
proxies:
- # namespace is the domain name used for following entries
  # This can be a subdomain, a domain or a full domain name
  # subdomain.example.org, example.org or example.org/subdomain
  namespace: atomys.codes
  # All entries of this namespace will be proxied to the following address
  # Key are the name and the entrypoint/path of your proxied packages
  # Value is the current URL of your package. The Destination URL must
  # end with a valid protocol.
  # Allowed protocol are: "bzr", "fossil", "git", "hg", "svn".
  entries:
    # Root redirection can be catch with "-" or "/" as key
    # Will responds to the following URL: atomys.codes
    -: https://github.com/42Atomys/vanity-go.git
    # Will responds to the following URL: atomys.codes/vanity-go
    vanity-go: https://github.com/42Atomys/vanity-go.git
    # Will responds to the following URL: atomys.codes/dns-updater
    dns-updater: https://github.com/42Atomys/dns-updater.git
    # Will responds to the following URL: atomys.codes/subpath/gw2api-go
    subpath/gw2api-go: https://gitlab.com/Atomys/gw2api-go.git